from tkinter import*
from tkinter import messagebox
from tkinter import ttk
import tkinter as tk
import mysql.connector
con=mysql.connector.connect(host='localhost',user='root',password='2468',database='airlines')
rootp=Tk()
rootp.title("INDIGO AIRLINES")
rootp.configure(bg="Black")
rootp.iconbitmap('D:\indigo1.ico')
Label(rootp,text="Welcome To Our Airlines!",font="Bold 40",bg='white').pack()
def cancl():
    rootp.destroy()
    root2=Tk()
    root2.title("Welcome To our Cancellation System")
    root2.configure(bg="Black")
    root2.iconbitmap('D:\indigo1.ico')
    Label(root2,text="Enter Registration Number",font="Bold 15",bg="sky blue").pack(padx=10,pady=15)
    e1=Entry(root2,font="Bold 15")
    e1.pack(padx=10,pady=15)
    Label(root2,text="Day Of Flight",font="Bold 15",bg="sky blue").pack(pady=15)
    w2=ttk.Combobox(root2,font="Bold 15",values=["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"])
    w2.pack(pady=15)
    Label(root2,text="Select Boarding",font="Bold 15",bg="sky blue").pack(pady=15)
    w3=ttk.Combobox(root2,font="Bold 15",values=["Chennai(MAA)","Bengaluru(BLR)","Mumbai(BOM)","Delhi(DEL)","Jaipur(JAI)","Hyderabad(HYD)","Thiruvananthapuram(TRV)","Ahmedabad(AMD)"])
    w3.pack(pady=15)
    def cancld():
        d=e1.get()
        b=w2.get()
        c=w3.get()
        cur=con.cursor()
        con.commit()
        if d=='' or b=='' or c=='':
             messagebox.showerror("Oops","You can't Enter the leave any field empty")
        else:
            cur.execute("delete from common where adno={} and Boarding='{}' and Day_Of_Flight='{}'".format(d,b,c))
            cur.execute("select * from common")
            messagebox.showinfo("Cancellation Terminal","your reservation is cancelled")
    Bc=Button(root2,text="Cancel Reservation",command=cancld,font="Bold 15").pack(pady=15)
    root2.mainloop()
def srch():
    rootp.destroy()
    root4=Tk()
    frame = Frame(root4)
    frame.pack()
    root4.title("Welcome,Search flights")
    root4.configure(bg="Black")
    root4.iconbitmap('D:\indigo1.ico')
    root4.geometry("450x400")
    Label(root4,text="Enter Boarding",font="Bold 25",bg="sky blue").pack(padx=10,pady=15)
    w1=ttk.Combobox(root4,font="Bold 25",values=["Chennai(MAA)","Bengaluru(BLR)","Mumbai(BOM)","Delhi(DEL)","Jaipur(JAI)","Hyderabad(HYD)","Thiruvananthapuram(TRV)","Ahmedabad(AMD)"])
    w1.pack(padx=10,pady=15)
    Label(root4,text="Select Destination",font="Bold 25",bg="sky blue").pack(pady = 15)
    w2=ttk.Combobox(root4,font="Bold 25",values=["Chennai(MAA)","Bengaluru(BLR)","Mumbai(BOM)","Delhi(DEL)","Jaipur(JAI)","Hyderabad(HYD)","Thiruvananthapuram(TRV)","Ahmedabad(AMD)"])
    w2.pack(pady = 15)
    def srchdet():
        a=w1.get()
        b=w2.get()
        print(a,b)
        cur=con.cursor()

        if a=='' or b=='':
            messagebox.showerror("Error","Cant leave any field empty")
        else:
             if a!=b:
                 cur.execute("create table if not exists eco(flightno varchar(30) primary key,Origin varchar(20),Destination varchar(50),Days_Of_Operation varchar(20),Departure varchar(10),Arrival varchar(50))")
                 cur.execute("insert ignore into eco values('6E 246/6E 2519','Ahmedabad(AMD)','Chennai(MAA)','Except Sunday','14:35','00:40')")
                 cur.execute("insert ignore into eco values('6E 313/6E 907','Ahmedabad(AMD)','Chennai(MAA)','Daily','18:40','23:40')")
                 cur.execute("insert ignore into eco values('6E 383/6E 413','Ahmedabad(AMD)','Bengaluru(BLR)','Daily','22:00','23:55')")
                 cur.execute("insert ignore into eco values('6E 947/6E 477','Ahmedabad(AMD)','Bengaluru(BLR)','Except Friday','22:50','00:25')")
                 cur.execute("insert ignore into eco values('6E 158','Ahmedabad(AMD)','Delhi(DEL)','Daily','06:10','07:45')")
                 cur.execute("insert ignore into eco values('6E 202','Ahmedabad(AMD)','Delhi(DEL)','Except Saturday','16:10','17:45')")
                 cur.execute("insert ignore into eco values('6E 313/6E 5384','Ahmedabad(AMD)','Hyderabad(HYD)','Except Monday','16:40','18:00')")
                 cur.execute("insert ignore into eco values('6E 214/6E 821','Ahmedabad(AMD)','Hyderabad(HYD)','Daily','09:15','11:00')")
                 cur.execute("insert ignore into eco values('6E 158/6E 212','Ahmedabad(AMD)','Jaipur(JAI)','Daily','06:10','07:30')")
                 cur.execute("insert ignore into eco values('6E 237','Ahmedabad(AMD)','Jaipur(JAI)','Every Tuesday','19:10','20:30')")
                 cur.execute("insert ignore into eco values('6E 5363','Ahmedabad(AMD)','Mumbai(BOM)','Daily','10:00','11:20')")
                 cur.execute("insert ignore into eco values('6E 6343','Ahmedabad(AMD)','Mumbai(BOM)','Every Monday','13:15','14:40')")
                 cur.execute("insert ignore into eco values('6E 153/6E 873','Ahmedabad(AMD)','Thiruvananthapuram(TRV)','Daily','20:00','22:00')")
                 cur.execute("insert ignore into eco values('6E 823/6E 7251','Ahmedabad(AMD)','Thiruvananthapuram(TRV)','Except Sunday','09:00','11:00')")
                 cur.execute("insert ignore into eco values('6E 156/6E 995','Chennai(MAA)','Ahmedabad(AMD)','Daily','20:55','22:55')")
                 cur.execute("insert ignore into eco values('6E 5005/6E 6373','Chennai(MAA)','Ahmedabad(AMD)','Except Saturday','12:40','14:40')")
                 cur.execute("insert ignore into eco values('6E 232','Chennai(MAA)','Bengaluru(BLR)','Daily','21:25','22:50')")
                 cur.execute("insert ignore into eco values('6E 238','Chennai(MAA)','Bengaluru(BLR)','Except Tuesday','13:00','14:05')")
                 cur.execute("insert ignore into eco values('6E 797/6E 6616','Chennai(MAA)','Delhi(DEL)','Daily','07:55 ','10:30')")
                 cur.execute("insert ignore into eco values('6E 2859/6E 396','Chennai(MAA)','Delhi(DEL)','Every Tuesday','12:05','15:10')")
                 cur.execute("insert ignore into eco values('6E 156 ','Chennai(MAA)','Hyderabad(HYD)','Daily','20:55','22:20')")
                 cur.execute("insert ignore into eco values('6E 271/6E 684','Chennai(MAA)','Hyderabad(HYD)','Except Thursday','09:20','11:20')")
                 cur.execute("insert ignore into eco values('6E 237/6E 237','Chennai(MAA)','Jaipur(JAI)','Daily','16:10','19:30')")
                 cur.execute("insert ignore into eco values('6E 271/6E 469','Chennai(MAA)','Jaipur(JAI)','Except Saturday','09:20','12:20')")
                 cur.execute("insert ignore into eco values('6E 156/6E 235','Chennai(MAA)','Mumbai(BOM)','Daily','10:00','11:45')")
                 cur.execute("insert ignore into eco values('6E 251/6E 150','Chennai(MAA)','Mumbai(BOM)','Except Tuesday','9:30','11:00')")
                 cur.execute("insert ignore into eco values('6E 281/6E 160','Chennai(MAA)','Thiruvananthapuram(TRV)','Daily','11:00','12:00')")
                 cur.execute("insert ignore into eco values('6E 510/6E 210','Chennai(MAA)','Thiruvananthapuram(TRV)','Every Monday','13:30','14:30')")
                 cur.execute("insert ignore into eco values('6E 149/6E 995','Bengaluru(BLR)','Ahmedabad(AMD)','Daily','14:30','15:45')")
                 cur.execute("insert ignore into eco values('6E 262/6E 6719','Bengaluru(BLR)','Ahmedabad(AMD)','Except Wednesday','17:45','19:00')")
                 cur.execute("insert ignore into eco values('6E 233','Bengaluru(BLR)','Chennai(MAA)','Daily','12:00','13:05')")
                 cur.execute("insert ignore into eco values('6E 237','Bengaluru(BLR)','Chennai(MAA)','Every Monday','00:00','01:30')")
                 cur.execute("insert ignore into eco values('6E 201/6E 3102','Bengaluru(BLR)','Delhi(DEL)','Daily','5:00','7:00')")
                 cur.execute("insert ignore into eco values('6E 2032 ','Bengaluru(BLR)','Delhi(DEL)','Except Sunday','17:00','19:00')")
                 cur.execute("insert ignore into eco values('6E 262','Bengaluru(BLR)','Hyderabad(HYD)','Daily','2:30','3:30')")
                 cur.execute("insert ignore into eco values('6E 635','Bengaluru(BLR)','Hyderabad(HYD)','Every Thursday','14:00','15:00')")
                 cur.execute("insert ignore into eco values('6E 469 ','Bengaluru(BLR)','Jaipur(JAI)','Daily','9:00','11:30')")
                 cur.execute("insert ignore into eco values('6E 346/6E 504','Bengaluru(BLR)','Jaipur(JAI)','Every Monday','21:00','23:30')")
                 cur.execute("insert ignore into eco values('6E 194/6E 813','Bengaluru(BLR)','Mumbai(BOM)','Daily','6:05','7:05')")
                 cur.execute("insert ignore into eco values('6E 414','Bengaluru(BLR)','Mumbai(BOM)','Except Saturday','18:05','19:05')")
                 cur.execute("insert ignore into eco values('6E 273','Bengaluru(BLR)','Thiruvananthapuram(TRV)','Daily','20:00','21:10')")
                 cur.execute("insert ignore into eco values('6E 873','Bengaluru(BLR)','Thiruvananthapuram(TRV)','Every Thursday','8:00','9:10')")
                 cur.execute("insert ignore into eco values('6E 213','Mumbai(BOM)','Ahmedabad(AMD)','Daily','16:15','17:15')")
                 cur.execute("insert ignore into eco values('6E 639','Mumbai(BOM)','Ahmedabad(AMD)','Every Friday','4:15','5:15')")
                 cur.execute("insert ignore into eco values('E 768 ','Mumbai(BOM)','Chennai(MAA)','Daily','11:15','12:30')")
                 cur.execute("insert ignore into eco values('6E 715/6E 237','Mumbai(BOM)','Chennai(MAA)','Except Friday','23:15','00:30')")
                 cur.execute("insert ignore into eco values('6E 199','Mumbai(BOM)','Bengaluru(BLR)','Daily','14:00','15:00')")
                 cur.execute("insert ignore into eco values('6E 5354','Mumbai(BOM)','Bengaluru(BLR)','Except sunday','2:00','3:00')")
                 cur.execute("insert ignore into eco values('6E 198','Mumbai(BOM)','Delhi(DEL)','Daily','8:00','10:00')")
                 cur.execute("insert ignore into eco values('6E 5336','Mumbai(BOM)','Delhi(DEL)','Except wedesday','20:00','22:00')")
                 cur.execute("insert ignore into eco values('6E 461 ','Mumbai(BOM)','Hyderabad(HYD)','Daily','15:00','16:30')")
                 cur.execute("insert ignore into eco values('6E 496/6E 496','Mumbai(BOM)','Hyderabad(HYD)','Every Thursday','3:00','4:30')")
                 cur.execute("insert ignore into eco values('6E 521','Mumbai(BOM)','Jaipur(JAI)','Daily','20:25','22:25')")
                 cur.execute("insert ignore into eco values('6E 6284/6E 736','Mumbai(BOM)','Jaipur(JAI)','Every Monday','8:25','10:25')")
                 cur.execute("insert ignore into eco values('6E 461/6E 6319 ','Mumbai(BOM)','Thiruvananthapuram(TRV)','Daily','9:30','11:00')")
                 cur.execute("insert ignore into eco values('6E 691','Mumbai(BOM)','Thiruvananthapuram(TRV)','Except Monday','21:30','23:00')")
                 cur.execute("insert ignore into eco values('6E 2023','Delhi(DEL)','Ahmedabad(AMD)','Daily','4:30','6:00')")
                 cur.execute("insert ignore into eco values('6E 161','Delhi(DEL)','Ahmedabad(AMD)','Except Tuesday','16:30','18:00')")
                 cur.execute("insert ignore into eco values('6E 2028','Delhi(DEL)','Chennai(MAA)','Daily','10:00','13:00')")
                 cur.execute("insert ignore into eco values('6E 2859','Delhi(DEL)','Chennai(MAA)','Every saturday','22:00','1:00')")
                 cur.execute("insert ignore into eco values('6E 2131','Delhi(DEL)','Bengaluru(BLR)','Daily','7:00','9:00')")
                 cur.execute("insert ignore into eco values('6E 2297','Delhi(DEL)','Bengaluru(BLR)','Except wednesday','19:00','21:00')")
                 cur.execute("insert ignore into eco values('6E 5055','Delhi(DEL)','Hyderabad(HYD)','Daily','19:30','21:30')")
                 cur.execute("insert ignore into eco values('6E 765','Delhi(DEL)','Hyderabad(HYD)','Every saturday','7:30','9:30')")
                 cur.execute("insert ignore into eco values('6E 736','Delhi(DEL)','Jaipur(JAI)','Daily','5:00','6:00')")
                 cur.execute("insert ignore into eco values('6E 5335','Delhi(DEL)','Mumbai(BOM)','Daily','17:00','19:00')")
                 cur.execute("insert ignore into eco values('6E 129','Delhi(DEL)','Mumbai(BOM)','Except sunday','5:00','7:00')")
                 cur.execute("insert ignore into eco values('6E 2131/6E 6519','Delhi(DEL)','Thiruvananthapuram(TRV)','Daily','00:00','3:00')")
                 cur.execute("insert ignore into eco values('6E 5031/6E 957','Delhi(DEL)','Thiruvananthapuram(TRV)','Every Monday','12:00','15:00')")
                 cur.execute("insert ignore into eco values('6E 987','Jaipur(JAI)','Ahmedabad(AMD)','Daily','10:00','11:00')")
                 cur.execute("insert ignore into eco values('6E 203/ 6E 213','Jaipur(JAI)','Ahmedabad(AMD)','Except Wednesday','22:00','23:00')")
                 cur.execute("insert ignore into eco values('6E 203/6E 2519','Jaipur(JAI)','Chennai(MAA)','Daily','13:00','16:00')")
                 cur.execute("insert ignore into eco values('6E 839/6E 237','Jaipur(JAI)','Chennai(MAA)','Every Sunday','1:00','4:00')")
                 cur.execute("insert ignore into eco values('6E 498','Jaipur(JAI)','Bengaluru(BLR)','Daily','13:30','16:00')")
                 cur.execute("insert ignore into eco values('6E 498','Jaipur(JAI)','Bengaluru(BLR)','Every Monday','1:30','16:00')")
                 cur.execute("insert ignore into eco values('6E 471','Jaipur(JAI)','Hyderabad(HYD)','Daily','2:00','4:30')")
                 cur.execute("insert ignore into eco values('6E 218/6E 821','Jaipur(JAI)','Hyderabad(HYD)','Except Wednesday','14:00','16:30')")
                 cur.execute("insert ignore into eco values('6E 203','Jaipur(JAI)','Delhi(DEL)','Daily','1:00','2:00')")
                 cur.execute("insert ignore into eco values('6E 6E 218/6E 533','Jaipur(JAI)','Delhi(DEL)','Every Friday','13:00','14:00')")
                 cur.execute("insert ignore into eco values('6E 218','Jaipur(JAI)','Mumbai(BOM)','Daily','15:30','17:00')")
                 cur.execute("insert ignore into eco values('6E 201/6E 219','Jaipur(JAI)','Mumbai(BOM)','Except Sunday','3:30','5:00')")
                 cur.execute("insert ignore into eco values('6E 839/6E 379','Jaipur(JAI)','Thiruvananthapuram(TRV)','Daily','16:00','19:30')")
                 cur.execute("insert ignore into eco values('6E 438','Jaipur(JAI)','Thiruvananthapuram(TRV)','Every Monday','4:00','7:30')")
                 cur.execute("insert ignore into eco values('6E 644','Hyderabad(HYD)','Ahmedabad(AMD)','Daily','5:00','7:00')")
                 cur.execute("insert ignore into eco values('6E 6718','Hyderabad(HYD)','Ahmedabad(AMD)','Every thursady','17:00','19:00')")
                 cur.execute("insert ignore into eco values('6E 188','Hyderabad(HYD)','Chennai(MAA)','Daily','9:00','10:00')")
                 cur.execute("insert ignore into eco values('6E 381','Hyderabad(HYD)','Chennai(MAA)','Except Sunday','21:00','22:00')")
                 cur.execute("insert ignore into eco values('6E 827','Hyderabad(HYD)','Bengaluru(BLR)','Daily','9:30','10:30')")
                 cur.execute("insert ignore into eco values('6E 6505','Hyderabad(HYD)','Bengaluru(BLR)','Every Saturday','21:30','22:30')")
                 cur.execute("insert ignore into eco values('6E 467','Hyderabad(HYD)','Jaipur(JAI)','Daily','10:00','12:00')")
                 cur.execute("insert ignore into eco values('6E 5045/6E 736','Hyderabad(HYD)','Jaipur(JAI)','Except Monday','22:00','00:00')")
                 cur.execute("insert ignore into eco values('6E 6468','Hyderabad(HYD)','Delhi(DEL)','Daily','10:30','12:30')")
                 cur.execute("insert ignore into eco values('6E 6685','Hyderabad(HYD)','Delhi(DEL)','Every Monday','22:30','00:30')")
                 cur.execute("insert ignore into eco values('6E 231','Hyderabad(HYD)','Mumbai(BOM)','Daily','11:00','12:30')")
                 cur.execute("insert ignore into eco values('6E 587/6E 389','Hyderabad(HYD)','Mumbai(BOM)','Every Sunday','23:00','00:30')")
                 cur.execute("insert ignore into eco values('6E 6319','Hyderabad(HYD)','Thiruvananthapuram(TRV)','Daily','23:30','1:00')")
                 cur.execute("insert ignore into eco values('6E 151/6E 379','Hyderabad(HYD)','Thiruvananthapuram(TRV)','Every Monday','11:30','13:00')")
                 cur.execute("insert ignore into eco values('6E 335/6E 6719','Thiruvananthapuram(TRV)','Ahmedabad(AMD)','Daily','10:00','12:00')")
                 cur.execute("insert ignore into eco values('6E 6147/6E 452','Thiruvananthapuram(TRV)','Ahmedabad(AMD)','Every Wednesday','22:00','00:00')")
                 cur.execute("insert ignore into eco values('6E 6344','Thiruvananthapuram(TRV)','Chennai(MAA)','Daily','8:00','9:00')")
                 cur.execute("insert ignore into eco values('6E 6147/6E 6191','Thiruvananthapuram(TRV)','Chennai(MAA)','Every Friday','20:00','21:00')")
                 cur.execute("insert ignore into eco values('6E 6147/6E 427','Thiruvananthapuram(TRV)','Bengaluru(BLR)','Daily','6:00','7:10')")
                 cur.execute("insert ignore into eco values('6E 6344/6E 6192','Thiruvananthapuram(TRV)','Bengaluru(BLR)','Every Thursday','18:00','19:10')")
                 cur.execute("insert ignore into eco values('6E 335/6E 467','Thiruvananthapuram(TRV)','Jaipur(JAI)','Daily','6:00','9:30')")
                 cur.execute("insert ignore into eco values('6E 176/6E 207','Thiruvananthapuram(TRV)','Jaipur(JAI)','Every Saturday','18:00','21:30')")
                 cur.execute("insert ignore into eco values('6E 6147/6E 2625','Thiruvananthapuram(TRV)','Delhi(DEL)','Daily','11:00','14:00')")
                 cur.execute("insert ignore into eco values('6E 176/6E 6613','Thiruvananthapuram(TRV)','Delhi(DEL)','Except Thursday','23:00','2:00')")
                 cur.execute("insert ignore into eco values('6E 7222/6E 184','Thiruvananthapuram(TRV)','Mumbai(BOM)','Daily','12:00','13:30')")
                 cur.execute("insert ignore into eco values('6E 6147/6E 426','Thiruvananthapuram(TRV)','Mumbai(BOM)','Every Monday','00:00','1:30')")
                 cur.execute("insert ignore into eco values('6E 7146/6E 2783','Thiruvananthapuram(TRV)','Hyderabad(HYD)','Daily','4:00','5:30')")
                 cur.execute("insert ignore into eco values('6E 7146/6E 624','Thiruvananthapuram(TRV)','Hyderabad(HYD)','Every Friday','16:00','17:30')")
                 com = "select * from eco where Origin='{}' and Destination='{}'".format(a,b)
                 print(com)
                 cur.execute(com)
                 e=cur.fetchall()
                 print(e)
                 root2=tk.Tk()
                 root2.title("Flights Available Are")
                 root2.geometry("1000x100")
                 root2.iconbitmap('D:\indigo1.ico')
                 tree = ttk.Treeview(root2, column=("c1", "c2", "c3","c4","c5","c6"), show='headings')
                 tree.column("#1", anchor=tk.CENTER)
                 tree.heading("#1", text="Flight Number")
                 tree.column("#2", anchor=tk.CENTER)
                 tree.heading("#2", text="Origin")
                 tree.column("#3", anchor=tk.CENTER)
                 tree.heading("#3", text="Destination")
                 tree.column("#4", anchor=tk.CENTER)
                 tree.heading("#4", text="Days Of Operation")
                 tree.column("#5", anchor=tk.CENTER)
                 tree.heading("#5", text="Departure")
                 tree.column("#6", anchor=tk.CENTER)
                 tree.heading("#6", text="Arrival")
                 tree.pack()
                 for row in e:
                     print(row)
                     tree.insert("",tk.END,values=row)
                 root2.mainloop()   
             else:           
                messagebox.showerror("Oops","boarding and destination can't be same,No flights are available")
    Bs=Button(root4,text="search",font="Bold 25",command=srchdet).pack(pady=15)            
    root4.mainloop()
def bookf():
    rootp.destroy()
    root=Tk()
    root.title('Flight search And booking')
    root.geometry("700x700")
    root.configure(bg="Black")
    root.iconbitmap('D:\indigo1.ico')
    Label(root,text="Enter Boarding",font="Bold 16",bg="sky blue").pack(padx=10,pady=15)
    w=ttk.Combobox(root,font="Bold 16",values=["Chennai(MAA)","Bengaluru(BLR)","Mumbai(BOM)","Delhi(DEL)","Jaipur(JAI)","Hyderabad(HYD)","Thiruvananthapuram(TRV)","Ahmedabad(AMD)"])
    w.pack(padx=10,pady=15)
    Label(root,text='Enter Destination',font="Bold 16",bg="sky blue").pack(pady = 15)
    w1=ttk.Combobox(root,font="Bold 16",values=["Chennai(MAA)","Bengaluru(BLR)","Mumbai(BOM)","Delhi(DEL)","Jaipur(JAI)","Hyderabad(HYD)","Thiruvananthapuram(TRV)","Ahmedabad(AMD)"])
    w1.pack(pady = 15)
#e3=Entry(root,width=20,justify='right')
#e3.grid(row=3,column=1)
    Label(root,text='Enter  Registration Number',font='Bold 16',bg="sky blue").pack(pady = 15)
    e=Entry(root,font="Bold 16")
    e.pack(pady = 15)
    Label(root,text='No. Of Passengers',font="Bold 16",bg="sky blue").pack(pady = 15)
    w2=Entry(root,font="Bold 16")
    w2.pack(pady=15)
    Label(root,text='Day Of Flight',font="Bold 16",bg="sky blue").pack(pady=15)
    f1=ttk.Combobox(root,font="Bold 16",values=["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"])
    f1.pack(pady=15)
    def booked():
        a=w.get()
        b=w1.get()
        c=e.get()
        d=w2.get()
        g=f1.get()
    
        cur=con.cursor()
        if a=='' or b=='' or c=='' or d=='' or g=='':
            messagebox.showerror("OOPS","you can't leave any field empty")
        else :
            cur.execute("create table if not exists common(Boarding varchar(20),Destination varchar(20),adno int primary key,no_of_passengers int,Day_Of_Flight varchar(20))")
            if a!=b:
                cur.execute("insert ignore into common values('{}','{}',{},{},'{}')".format(a,b,c,d,g))
                messagebox.showinfo("congrats","your seat has been reserved")
                con.commit()
                cur.execute("select * from common where adno={}".format(c))
            else :
                messagebox.showerror("oops!,Please Enter Your Details Correctly")
    Bi=Button(root,text="Book",command=booked,font="Bold 15").pack(pady=15)
    root.mainloop()
    
B1=Button(rootp,text="Search Flight",font = (40),command=srch,bg="sky blue",height=4,width=35).pack(padx=10,pady=20)
B2=Button(rootp,text="Book Flight",font = (40),command=bookf,bg="sky blue",height=4,width=35).pack(pady = 20)
B3=Button(rootp,text="Cancel Booking",font = (40),command=cancl,bg="sky blue",height=4,width=35).pack(pady = (20,60))




rootp.mainloop()
    
